version: "~> 1.0"
git:
  depth: 1
  quiet: true
language: java
jdk:
  - openjdk17
branches:
  only:
    - develop
    - support/4.1.x
    - support/4.0.x
    - master
cache:
  directories:
    - "$HOME/.m2"
notifications:
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
before_install:
  - mkdir -p $HOME/.m2
  - cp .travis-settings.xml $HOME/.m2/settings.xml
install: skip
script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c "mvn deploy --settings .travis-settings.xml"; fi
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn clean install"; fi
env:
  global:
    - secure: "BaTKV/oqZr5GL0/7BrvtzsJ67GbMV7oHZ96Yypkhz9WPhC2V7QsBySa/c3zfROcd4NfOdWe76EvVWlE2b6PFPE2kA99DJLoqcWn5XwBOVrgbj5bKVYlE7vKnQ2qA8SQtlnuV/5ocbW8kv+5WSl4qdJbqz1V3alJoYr+BesUYlfg="
    - secure: "d3suJ68qM6fg3Zekbpmmq3fPR35lCk/Qig8Z5SM7WAlj9SKsFoS8+YLJ5wc7zq2I6iQ+Y5PEWPcLHr8CbogT7TSTyk4MGZtN6l4MB74ZyuR4DnVObitJcwn3tmrZOcJdekYegko+Wmost4pZrldiuJ+3/W8KHQdLxWCOvnvY9hM="
